config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  delete "logout" => "sessions#destroy"

  resources :words, only: :index
  resources :lessons, only: :index
  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :sessions, only: [:new, :create]
  resources :categories, only: [:index, :new, :create]
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "categories#index"
    resources :users
    resources :categories
    resources :words, only: [:update, :destroy, :create]
  end
  resources :lessons, except: [:index, :destroy, :edit]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @categories = Category.all
      @words = Word.send("by_learned", current_user.id, @categories.map(&:id)).
        paginate page: params[:page]
      @count = @words.present? ? @words.count : 0
      @activities = current_user.activities.order(created_at: :DESC).
        paginate page: params[:page], per_page: Settings.per_page
    end
  end
end

app/views/static_pages/home.html.erb
<%= provide :title, t("home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-3">
      <section class="user_info">
        <%= link_to avatar_for(current_user, Settings.avatar.height,
          Settings.avatar.width), current_user %>
      </section>
      <section class="name">
        <p><%= link_to current_user.name, current_user %></p>
        <p><%= link_to t("user.number_word", word_count: @count),
          words_path(condition: "learned") %></p>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <div class="col-md-9">
      <div class="col-md-6 col-md-offset-4">
        <p>
          <%= link_to t("word.word_all"), words_path,
            class: "btn btn-success btn-lg"%>
          <%= link_to t("categories.lessons"), categories_path,
            class: "btn btn-warning btn-lg" %>
        </p>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="list-group">
            <li class="list-group-item active"><%= t "user.activities" %></li>
            <% if @activities.any? %>
              <%= render @activities %>
            <% else %>
              <li class="list-group-item">
                <h4>
                  <span class="text-info"><%= t "views.no_activity" %></span>
                </h4>
              </li>
            <% end %>
          </ul>
          <%= will_paginate @activities %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="row content">
    <div class="col-md-10 col-md-offset-1 text-center">
      <div class="jumbotron">
        <h2><%= t "views.static_pages.welcome" %></h2>
      </div>
      <hr>
      <%= link_to t("views.signup.signup_now"), new_user_path,
        class: "btn btn-lg btn-primary" %>
    </div>
  </div>
<% end %>