config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  delete "logout" => "sessions#destroy"

  resources :words, only: :index
  resources :lessons, only: :index
  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :sessions, only: [:new, :create]
  resources :categories, only: [:index, :new, :create]
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "categories#index"
    resources :users
    resources :categories
    resources :words, only: [:update, :destroy, :create]
  end
  resources :lessons, except: [:index, :destroy, :edit]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form" %> <%= pluralize object.errors.count, t("error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= user_relationship_path(@user, relationship: "following") %>" >
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "views.follow.following" %>
  </a>
  <a href="<%= user_relationship_path(@user, relationship: "followers") %>" >
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "views.follow.followers" %>
  </a>
</div>