config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  delete "logout" => "sessions#destroy"

  resources :words, only: :index
  resources :lessons, only: :index
  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :sessions, only: [:new, :create]
  resources :categories, only: [:index, :new, :create]
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "categories#index"
    resources :users
    resources :categories
    resources :words, only: [:update, :destroy, :create]
  end
  resources :lessons, except: [:index, :destroy, :edit]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController <ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_category, except: [:new, :create]

  def index
    @categories = Category.all.paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "admin.flash.created_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "admin.flash.created_fail"
      render :new
    end
  end

  def edit
  end

  def show
    if params[:word_id].nil?
      @word = Word.new
      4.times{
        @word.word_answers.build
      }
    else
      @word = Word.find_by id: params[:word_id]
    end
    @words = @category.words.paginate page: params[:page]
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "admin.flash.edited_success"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "admin.flash.edited_fail"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "admin.flash.deleted_success"
    else
      flash[:danger] = t "admin.flash.deleted_fail"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  def index
    @categories = Category.all.paginate page: params[:page]
  end
end

app/views/admin/categories/_word.html.erb
<div class="col-md-6 panel panel-default">
  <h3>
    <%= link_to t("admin.words.new"),
      admin_category_path(@category, word_id: nil) %>
  </h3>
  <%= form_for [:admin, @word] do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <p><%= f.label :content, t("admin.words.content") %></p>
    <p><%= f.text_field :content, class: "form-control" %></p>
    <%= f.hidden_field :category_id, value: @category.id %>
    <%= f.fields_for :word_answers do |builder| %>
      <%= render "word_answer_fields", f: builder %>
    <% end %>
    <p><%= link_to_add_fields t("admin.words.add_answer"),
      f, :word_answers %></p>
    <%= f.submit t("admin.words.submit"), class: "btn btn-default
      col-md-4 col-md-offset-4" %>
  <% end %>
</div>

app/views/admin/categories/_word_answer_fields.html.erb
<fieldset>
  <%= render "shared/error_messages", object: f.object %>
  <p>
    <%= f.label :content, t("admin.words.answer_content") %>
    <%= f.check_box :correct, class: "check-change" %>
    <%= t "admin.words.correct" %>
    <%= f.hidden_field :_destroy %>
    <%= link_to t("admin.words.remove"), "#", class: "remove_fields" %>
  </p>
  <%= f.text_field :content, class: "form-control" %><br>
</fieldset>

app/views/admin/categories/_word_list.html.erb
<div class="col-md-12 panel panel-default">
  <h3><%= t "admin.category.word_list" %></h3>
  <p><%= "#{@words.count} #{t "admin.words.words"}" %></p>
  <ul class="list-unstyled">
    <% if @words.present? %>
      <%= will_paginate @words %>
      <% @words.each do |word| %>
        <div class="col-md-6">
          <li><%= word.content %></li>
        </div>
        <div class="col-md-6">
          <p>
            <%= link_to t("admin.words.edit"),
              admin_category_path(@category, word_id: word.id) %>
            <%= link_to t("admin.words.delete"), admin_word_path(word),
              method: :delete, data: {confirm: t("admin.words.confirm")} %>
          </p>
        </div>
      <% end %>
    <% end %>
    <%= will_paginate @words %>
  </ul>
</div>

app/views/admin/categories/edit.html.erb
<% provide :title, t("admin.category.edit") %>
<h1><%= t "admin.category.edit" %></h1>

<div class = "row">
  <div class= "col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name, t("admin.category.name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t("admin.category.description") %>
      <%= f.text_area :description, class: "form-control" %>

      <%= f.submit t("admin.category.update"), class: "btn btn-default col-md-3" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<%= provide :title, t("views.layouts.categories") %>

<h4>
  <%= link_to t("admin.category.new"), new_admin_category_path,
    class: "btn btn-default" %>
</h4>

<div class="row">
  <div class="col-md-12">
    <li class="list-group-item default"><%= t "views.all_categories" %></li>
    <ul class="list-group">
      <% @categories.each do |category| %>
        <li class="list-group-item ">
          <%= link_to category.name, admin_category_path(category) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t("admin.category.new") %>

<div class = "col-md-12">
  <div class="col-md-6 panel panel-default col-md-offset-3">
    <h1><%= t "admin.category.new" %></h1>
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name, t("admin.category.name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, t("admin.category.description") %>
      <%= f.text_area :description, class: "form-control" %>

      <h1>
        <%= f.submit t("admin.category.create"),
        class: "btn btn-primary col-md-3" %>
      </h1>
    <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<div class="col-md-12">
  <div class="col-md-6">
    <div class="col-md-12 panel panel-default">
      <h3><%= @category.name %></h3>
      <p>
        <%= link_to t("admin.edit"), edit_admin_category_path(@category) %>
        <%= link_to t("admin.delete"), admin_category_path(@category),
          method: :delete, data: {confirm: t("admin.category_delete")} %>
      </p>
      <p><%= t("admin.categories.description") + ": " +
        @category.description %></p>
    </div>
    <%= render "word_list" %>
  </div>
  <%= render "word" %>
</div>