config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  delete "logout" => "sessions#destroy"

  resources :words, only: :index
  resources :lessons, only: :index
  resources :users do
    get "/:relationship" => "relationships#index", as: :relationship,
      constraints: {relationship: /(following|followers)/}
  end
  resources :sessions, only: [:new, :create]
  resources :categories, only: [:index, :new, :create]
  resources :relationships, only: [:index, :create, :destroy]
  namespace :admin do
    root "categories#index"
    resources :users
    resources :categories
    resources :words, only: [:update, :destroy, :create]
  end
  resources :lessons, except: [:index, :destroy, :edit]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  QUERY_SEARCH_ADMIN = "id in (select users.id from users
    where users.name LIKE ? AND users.admin = 't')"
  QUERY_SEARCH_USER = "id in (select users.id from users
    where users.name LIKE ? AND (users.admin = 'f' OR users.admin is null))"
  QUERY_SEARCH_ALL = "id in (select users.id from users
    where users.name LIKE ?)"

  has_many :activities
  has_many :lessons
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
    foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true, length: {maximum: 50}
  validates :password, length: {minimum: 6}, allow_blank: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}

  has_secure_password
  mount_uploader :avatar, AvatarUploader

  scope :search_admin, -> (search_name){where QUERY_SEARCH_ADMIN,
    "%#{search_name}%"}
  scope :search_user, -> (search_name){where QUERY_SEARCH_USER,
    "%#{search_name}%"}
  scope :search_all, -> (search_name){where QUERY_SEARCH_ALL,
    "%#{search_name}%"}

  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated? remember_token
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :verify_admin
  before_action :find_user, except: [:index, :new, :create]

  def index
    name = params[:s_name].present? ? params[:s_name] : ""

    condition = if(params[:s_admin].present? && params[:s_user].present?)
      "all"
    elsif params[:s_admin].present?
      params[:s_admin]
    elsif params[:s_user].present?
      params[:s_user]
    else
      nil
    end

    if condition
      @users = User.send("search_#{condition}", name).paginate page: params[:page],
        per_page: Settings.users.per_page
    else
      @users = User.all.paginate page: params[:page],
        per_page: Settings.users.per_page
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "views.update.success"
      redirect_to admin_users_path
    else
      flash[:danger] = t "views.update.error"
      render :edit
    end
  end

  def destroy
    unless current_user? @user
      @user.destroy
      flash_for_destroy @user
    else
      flash[:warning] = t "admin.flash.user_cannot"
    end
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :avatar, :admin, :password, :password_confirmation
  end

  def find_user
    @user = User.find params[:id]
  end

  def flash_for_destroy params
    if params.destroyed?
      flash[:success] = t "admin.flash.deleted_success"
    else
      flash[:danger] = t "admin.flash.deleted_fails"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update]

  def index
    name = params[:s_name].present? ? params[:s_name] : ""

    condition = if params[:s_admin].present? && params[:s_user].present?
      "all"
    elsif params[:s_admin].present?
      params[:s_admin]
    elsif params[:s_user].present?
      params[:s_user]
    else
      nil
    end

    if condition
      @users = User.send("search_#{condition}", name).paginate page: params[:page],
        per_page: Settings.users.per_page
    else
      @users = User.all.paginate page: params[:page],
        per_page: Settings.users.per_page
    end
  end

  def show
    if logged_in?
      @categories = Category.all
      @words = Word.send("by_learned", @user.id, @categories.map(&:id)).
        paginate page: params[:page]
      @count = @words.present? ? @words.count : 0
      @activities = @user.activities.order(created_at: :DESC).
        paginate page: params[:page], per_page: Settings.per_page
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "views.signup.success"
      redirect_to new_session_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      flash[:success] = t "views.update.success"
      redirect_to @user
    else
      flash[:danger] = t "views.update.error"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :avatar, :password, :password_confirmation
  end

  def find_user
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size = Settings.avatar.size
    if user.present?
      gravatar_id = Digest::MD5::hexdigest user.email.downcase
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag gravatar_url, alt: user.name, class: "gravatar"
    end
  end

  def avatar_for user, height = Settings.height, width = Settings.width
    if user.avatar.blank?
      image_tag Settings.avatar.default, height: height, width: width
    else
      image_tag user.avatar_url(:thumb)
    end
  end
end

app/views/admin/users/_user.html.erb
<li class="list-group-item">
  <h4>
    <%= link_to avatar_for(user, Settings.avatar.height,
      Settings.avatar.width), user %>
    <%= link_to user.name, user %>
    <% unless current_user?user %>
      | <%= link_to t("admin.edit"), edit_admin_user_path(user) %>
      | <%= link_to t("admin.delete"), admin_user_path(user),
        method: :delete, data: {confirm: t("views.user.confirm")} %>
    <% end %>
  </h4>
</li>

app/views/admin/users/edit.html.erb
<% provide :title, t("views.update.update") %>

<div class = "row">
  <div class= "col-md-6 col-md-offset-3 panel panel-default">
    <h1><%= t "views.update.update" %></h1><br>
    <%= form_for @user do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <p>
        <%= f.label :avatar %>
        <div class="photo-preview">
          <% avatar_for @user, Settings.avatar.height, Settings.avatar.width %>
        </div>
        <%= f.file_field :avatar %>
      </p>
      <p>
        <%= f.label :name, t("views.signup.name") %>
        <%= f.text_field :name, class: "form-control" %>
      </p>
      <p>
        <%= f.label :email, t("views.signup.email") %>
        <%= f.email_field :email, class: "form-control" %>
      </p>
      <p>
        <%= f.label :password, t("views.signup.password") %>
        <%= f.password_field :password, class: "form-control" %>
      </p>
      <p>
        <%= f.label :password_confirmation,
          t("views.signup.password_confirmation") %>
        <%= f.password_field :password_confirmation, class: "form-control" %>
      </p>
      <p>
        <%= f.check_box :admin %>
        <%= t "admin.admin" %>
      </p>
      <p>
        <%= f.submit t("views.update.save_change"), class: "btn btn-default" %>
      </p>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("views.all_users") %>
<h1><%= t "views.all_users" %></h1>

<%= form_for users_path, method: :get do |f| %>
  <p>
    <%= text_field_tag :s_name, params[:s_name],
      placeholder: t("views.search_users") %>
    <%= check_box_tag :s_admin, :admin,
      (true if params[:s_admin] == "admin") %>
    <%= t "views.search.admin" %>
    <%= check_box_tag :s_user, :user,
      (true if params[:s_user] == "user") %>
    <%= t "views.search.user" %>
    <h4>
      <%= submit_tag t("views.search.submit"), name: nil %>
    </h4>
  </p>
<% end %>

<div class="row">
  <div class="col-md-12">
    <li class="list-group-item active"><%= t "views.all_users" %></li>
    <% if @users.present? %>
      <ul class="list-group">
        <% if @users.any? %>
          <%= render @users %>
        <% else %>
          <li class="list-group-item">
            <h4>
              <span class="text-info"><%= t "views.no_user" %></span>
            </h4>
          </li>
        <% end %>
      </ul>
      <%= will_paginate @users %>
    <% else %>
      <li class="list-group-item">
        <h4>
          <span class="text-info"><%= t "views.no_user" %></span>
        </h4>
      </li>
    <% end %>
  </div>
</div>